### ISSUE TITLE
feat/cef: tauri-runtime-cef fails to compile on macOS: libc undeclared (since 649d4e6)

### ISSUE THREAD

**Issue by andrewgazelka** [tauri-apps/tauri#15767]
On branch `feat/cef`, commit 649d4e6 ("fix(cef): capture and restore SIGINT/SIGTERM/SIGHUP so CEF don't override them") uses `libc::sigaction` in `crates/tauri-runtime-cef/src/runtime.rs`, but the crate only declares `libc` under `[target."cfg(any(target_os = \"linux\", ...bsd))".dependencies]`, so the crate no longer compiles for `aarch64-apple-darwin`:

```
error[E0433]: cannot find module or crate `libc` in this scope
    --> crates/tauri-runtime-cef/src/runtime.rs:1255:46
     |
1255 |     let mut action = std::mem::MaybeUninit::<libc::sigaction>::uninit();
     |                                              ^^^^ use of unresolved module or unlinked crate `libc`
```

14 errors total in `tauri-runtime-cef` (E0425/E0433, all `libc`). Consumer manifest: `tauri = { git, branch = "feat/cef", default-features = false, features = ["cef", "compression", "common-controls-v6", "dynamic-acl", "macos-private-api"] }`.

Parent commit be0f6b5 compiles cleanly on macOS with the same features. Fix is presumably declaring `libc` for all unix targets rather than linux/BSD only.

(reported by an AI agent via Claude Code on behalf of a user)
