### PR TITLE
fix: update time-rs to pass build on rust 1.80 (fix #10406)

### LINKED ISSUE #10406: [bug] Can't build Tauri CLI with Rust 1.80
### Describe the bug

After upgrade to Rust 1.80, building tauri cli fails.

See
https://github.com/time-rs/time/issues/693.

Working on a pull request with a lock update

### Reproduction

_No response_

### Expected behavior

_No response_

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.0 (051478957 2024-07-21)
    ✔ cargo: 1.80.0 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.0.0
    - npm: 10.5.1

[-] Packages
    - tauri [RUST]: no manifest (unknown lockfile)
    - tauri-build [RUST]: no manifest (unknown lockfile)
    - wry [RUST]: no manifest (unknown lockfile)
    - tao [RUST]: no manifest (unknown lockfile)
    - tauri-cli [RUST]: 2.0.0-beta.20
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20
```

### Stack trace

```text
~/code/tauri/tooling/cli ❖  cargo build                                                                                                                                   dev
   Compiling time v0.3.34
   Compiling tauri-cli v2.0.0-beta.22 (/Users/gman/code/tauri/tooling/cli)
error[E0282]: type annotations needed for `Box<_>`
  --> /Users/gman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ghost**
Ran `cargo update time` to bump time-rs to 0.3.36 in order to pass build with rust 1.80. See #10406

### CODE REVIEW

**Comment by ghost** [comment]
Clippy fix seems to be included [here](https://github.com/tauri-apps/tauri/pull/10394/files)

**Comment by FabianLars** [comment]
The linked PR also updated the lockfile so this PR is no-op now, sorry x) Thanks for contributing though!
