### ISSUE TITLE
[bug] macOS 10.13 compatibility dyld: Symbol not found: _NSHTTPCookieSameSiteLax

### ISSUE THREAD

**Issue by zefir1990** [tauri-apps/tauri#14201]
### Describe the bug

Using macOS "minimumSystemVersion": "10.13" in tauri.conf.json. 
App works ok on macOS 10.15+, but on macOS 10.13 got error:

`
dyld: Symbol not found: _NSHTTPCookieSameSiteLax
  Referenced from: /Applications/SuperCalls.app/Contents/MacOS/supercalls
  Expected in: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 in /Applications/SuperCalls/Contents/MacOS/supercalls
Abort trap: 6
`

Found that missing symbols related to tauri -> wry, cookie packages.
Missing symbols on macOS 10.13:

1. NSHTTPCookieSameSiteLax
2. NSHTTPCookieSameSitePolicy
3. NSHTTPCookieSameSiteStrict

### Reproduction

Using macOS "minimumSystemVersion": "10.13" in tauri.conf.json. 
Build tauri app, run on macOS 10.13

### Expected behavior

Tauri app works on macOS 10.13 with "minimumSystemVersion": "10.13" in tauri.conf.json

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 15.6.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.88.0 (6b00bc388 2025-06-23)
    ✔ cargo: 1.88.0 (873a06493 2025-05-10)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 24.2.0
    - npm: 11.4.2

[-] Packages
    - tauri 🦀: 2.8.4
    - tauri-build 🦀: 2.4.0
    - wry 🦀: 0.53.3
    - tao 🦀: 0.34.2
    - @tauri-apps/api : 2.3.0 (outdated, latest: 2.8.0)
    - @tauri-apps/cli : 2.3.1 (outdated, latest: 2.8.4)

[-] Plugins
    - tauri-plugin-clipboard-manager 🦀: 2.3.0
    - @tauri-apps/plugin-clipboard-manager : 2.2.1 (outdated, latest: 2.3.0)
    - tauri-plugin-notification 🦀: 2.3.1
    - @tauri-apps/plugin-notification : 2.2.1 (outdated, latest: 2.3.1)
    - tauri-plugin-process 🦀: 2.3.0
    - @tauri-apps/plugin-process : 2.2.0 (outdated, latest: 2.3.0)
    - tauri-plugin-single-instance 🦀: 2.3.3
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-shell 🦀: 2.3.1
    - @tauri-apps/plugin-shell : 2.2.0 (outdated, latest: 2.3.1)
    - tauri-plugin-os 🦀: 2.3.1
    - @tauri-apps/plugin-os : 2.2.0 (outdated, latest: 2.3.1)

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
`
dyld: Symbol not found: _NSHTTPCookieSameSiteLax
  Referenced from: /Applications/SuperCalls.app/Contents/MacOS/supercalls
  Expected in: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 in /Applications/SuperCalls/Contents/MacOS/supercalls
Abort trap: 6
`
```

**Comment by FabianLars** [comment]
Does the crash happen when you start the app or at a later point?

**Comment by zefir1990** [comment]
@FabianLars open in terminal /Applications/SuperCalls/Contents/MacOS/supercalls -> linker error.

**Comment by FabianLars** [comment]
Can you try again after adding this to your Cargo.toml file?
```toml
[patch.crates-io]
wry = { git = "https://github.com/tauri-apps/wry", branch = "fix/macos/symbol-not-found-1013" }
```
(may require you to run `cargo update` )

**Comment by zefir1990** [comment]
Ok, when my client respond I will try.

**Comment by clone206** [comment]
I was facing the exact same error in MacOS 10.13 (x86_64) so I tried the solution mentioned here (patched wry version in Cargo.toml). It prevented the error, but my app launched with an empty window. Nothing interesting in my app's logs, which appear to the right of the empty window in the attached image.

The app runs fine in Sequoia on apple silicon when built with the same wry patch.

**Edit:** also runs fine in MacOS 12 x86_64.

![Image](https://github.com/user-attachments/assets/3515f2f1-4988-404e-8f36-30a16cd5625e)

**Comment by FabianLars** [comment]
`cargo update wry` if you're using tauri v2.10 should pull in the fixes.
