### ISSUE TITLE
[bug] Lifecycle error occurred when registering plugins after migrating from v1 to v2

### ISSUE THREAD

**Issue by thep0y** [tauri-apps/tauri#8915]
### Describe the bug

When migrating from v1 to v2 using the CLI, after registering the 'shell' plugin, the compiler reports a lifecycle error when running the program with `tauri dev`.

Creating a project directly with v2 does not produce this compilation error.

```
error[E0107]: struct takes 0 lifetime arguments but 1 lifetime argument was supplied
   --> /Users/thepoy/.cargo/git/checkouts/plugins-workspace-fd0259fcb18f51ad/8645a02/plugins/shell/src/commands.rs:106:20
    |
106 |     command_scope: CommandScope<'_, crate::scope::ScopeAllowedCommand>,
    |                    ^^^^^^^^^^^^ -- help: remove this lifetime argument
    |                    |
    |                    expected 0 lifetime arguments
    |
note: struct defined here, with 0 lifetime parameters
   --> /Users/thepoy/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/tauri-2.0.0-beta.3/src/ipc/authority.rs:364:12
    |
364 | pub struct CommandScope<T: ScopeObject>(ScopeValue<T>);
    |            ^^^^^^^^^^^^

error[E0107]: struct takes 0 lifetime arguments but 1 lifetime argument was supplied
   --> /Users/thepoy/.cargo/git/checkouts/plugins-workspace-fd0259fcb18f51ad/8645a02/plugins/shell/src/commands.rs:107:19
    |
107 |     global_scope: GlobalScope<'_, crate::scope::ScopeAllowedCommand>,
    |                   ^^^^^^^^^^^ -- help: remove this lifetime argument
    |                   |
    |                   expected 0 lifetime arguments
    |
note: struct defined here, with 0 lifetime parameters
   --> /Users/thepoy/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/tauri-2.0.0-beta.3/src/ipc/authority.rs:404:12
    |
404 | pub struct GlobalScope<T: ScopeObject>(ScopeValue<T>);
    |            ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0107`.
```

### Reproduction

```rust
#[tokio::main]
async fn main() -> AlleyResult<()> {
    // ...

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![
            // ...
        ])
        .run(tauri::generate_context!())?;

    Ok(())
}
```

```toml
[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-shell = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tokio = { version = "1", features = ["macros"] }
# ...
```

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.3.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.11.1
    - pnpm: 8.15.1
    - npm: 10.2.4
    - bun: 1.0.22

[-] Packages
    - tauri [RUST]: 2.0.0-beta.3
    - tauri-build [RUST]: 2.0.0-beta.2
    - wry [RUST]: 0.36.0
    - tao [RUST]: 0.25.0
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 2.0.0-beta.2

[-] App
    - build-type: bundle
    - CSP: unset
    - devUrl: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by pewsheen** [comment]
The `shell` plugin is currently not updated to `beta.3`. It needs to be removed temporarily from your dependency.

Plugin update PR: https://github.com/tauri-apps/plugins-workspace/pull/971

**Comment by ken0x0a** [comment]
`completed` is misleading as the PR link (above) has not merged, and not published yet.

- https://github.com/tauri-apps/plugins-workspace/pull/971

**Comment by podarcis** [comment]
Just a heads up that this issue even breaks developing a fresh application using tauri-create-app `yarn create tauri-app --beta`.

**Comment by martpie** [comment]
> Just a heads up that this issue even breaks developing a fresh application using tauri-create-app yarn create tauri-app --beta.

Yes probably due to the PR above not being merged. I guess the create-tauri-app scripts take all latest versions, that are not compatible between each other right now

**Comment by cloook** [comment]
> Just a heads up that this issue even breaks developing a fresh application using tauri-create-app `yarn create tauri-app --beta`.

Yes, When I follow [`Create a Project`](https://beta.tauri.app/guides/create/) to make a new tauri-2.0.0 project, encountered the same problem.
