### ISSUE TITLE
[bug] [v2]error[E0599]: no method named `emit` found for reference `&AppHandle<_>` in the current scope  

### ISSUE THREAD

**Issue by zhanglun** [tauri-apps/tauri#12066]
### Describe the bug

I want to emit event to front when tray menu item clicked. in v1 `app.emit()` is ok but not work after migrated to v2.
here is my code.
```
pub fn create_tray(
  app: &mut App,
) -> Result<(), tauri::Error> {
  let about = MenuItemBuilder::new("About Pavo")
    .id("about")
    .build(app)
    .unwrap();

  let menu = MenuBuilder::new(app)
    .items(&[&about])
    .build()
    .unwrap();

  let _ = TrayIconBuilder::new()
    .menu(&menu)
    .on_menu_event(move |app, event| match event.id.as_ref() {
      "about" => {
        app.emit("go-to-about", ());
      }
      _ => {
        println!("menu item {:?} not handled", event.id);
      }
    })
    .build(app);
  Ok(())
}

```

Is there any detailed documentation for v2, similar to [v1](https://v1.tauri.app/v1/guides/features/events/)?

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 15.2.0 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.13.1
    - pnpm: 7.33.7
    - npm: 10.5.2

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - tauri-cli 🦀: 2.0.4
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-fs 🦀: 2.0.3
    - @tauri-apps/plugin-fs : not installed!
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.2.0
    - tauri-plugin-updater 🦀: 2.0.2
    - @tauri-apps/plugin-updater : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text
error[E0599]: no method named `emit` found for reference `&AppHandle<_>` in the current scope
   --> src/tray.rs:127:13
    |
127 |         app.emit("go-to-about", ());
    |             ^^^^
```

**Comment by FabianLars** [comment]
Is that the _full_ error? Right below what you cut off it should tell you what to do == import the `Emitter` trait via `use tauri::Emitter;`

> Is there any detailed documentation for v2, similar to [v1](https://v1.tauri.app/v1/guides/features/events/)?

https://v2.tauri.app/develop/calling-frontend/#event-system
