### ISSUE TITLE
[docs] npm migrate can't migrate js packages for plugins pulled from v1 branch

### ISSUE THREAD

**Issue by gknapp** [tauri-apps/tauri#10693]
I've encountered an error using [tauri-plugin-store-api](https://github.com/tauri-apps/tauri-plugin-store) when upgrading my app to 2.0.0-RC4. There's no mention in the [migration guide](https://v2.tauri.app/start/migrate/from-tauri-1) about the change to the V2 [Store plugin](https://v2.tauri.app/plugin/store).

Using the V1 `tauri-plugin-store-api` manifests as: `TypeError: window.__TAURI_IPC__ is not a function`

![image](https://github.com/user-attachments/assets/c2a83df8-5091-411c-b974-ff6f994a88f5)

This is the sources tab:

![image](https://github.com/user-attachments/assets/544810cf-64ee-43f2-9ad1-04bddad9fab2)

**Comment by FabianLars** [comment]
This error _should_ mean that the npm package for the store plugin is still on v1.

**Comment by gknapp** [comment]
> This error _should_ mean that the npm package for the store plugin is still on v1.

It should but it's been upgraded:

![image](https://github.com/user-attachments/assets/5fc0047f-9297-40dd-80b7-21f7a0a09355)

On the JS side I have v1 and v2 installed. I'll remove the v1 - should the migration script replace these and update calls to the v1 plugin to v2?

![image](https://github.com/user-attachments/assets/cf9fbffe-9cf4-4cd7-8cc7-19feed03a9e0)

**Comment by FabianLars** [comment]
> should the migration script replace these and update calls to the v1 plugin to v2?

Yes this is basically still https://github.com/tauri-apps/tauri/issues/10650 because the PR only touched on the rust packages.
