### ISSUE TITLE
When I updated to v1.0.0-beta.0，the app was blank

### ISSUE THREAD

**Issue by dibadibadiudiu** [tauri-apps/tauri#1793]
**Describe the bug**

When I updated to v1.0.0-beta.0, when I finished building the application and opened it, the app was blank。
`yarn tauri build --debug` show this error

[Error] Refused to load tauri://localhost/js/chunk-vendors.27b1331a.js because it appears in neither the script-src directive nor the default-src directive of the Content Security Policy.

but run `yarn tauri dev` is ok。

**To Reproduce**
1.`yarn tauri build --debug`
2.open app webview console

**Platform and Versions (please complete the following information):**
Operating System - Mac OS, version 11.2.3 X64

Node.js environment
  Node.js - 15.8.0
  @tauri-apps/cli - 1.0.0-beta-rc.4
  @tauri-apps/api - 1.0.0-beta-rc.3

Global packages
  npm - 7.5.1
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

**Comment by nothingismagick** [comment]
Can you paste the results of your `yarn tauri info` please?

**Comment by nothingismagick** [comment]
And perhaps try to add `'self'` at the end of the CSP declaration (proposed on our Discord).

**Comment by dibadibadiudiu** [comment]
Thank you for your prompt reply 🍺


Operating System - Mac OS, version 11.2.3 X64

Node.js environment
  Node.js - 15.8.0
  @tauri-apps/cli - 1.0.0-beta-rc.4
  @tauri-apps/api - 1.0.0-beta-rc.3

Global packages
  npm - 7.5.1
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/dist
/node_modules
/public
/src-tauri
/.git
/src

App
  tauri.rs - 1.0.0-beta.0
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
distDir - ../dist
devPath - http://localhost:8080

**Comment by nothingismagick** [comment]
Great. Can you try to edit your `tauri.conf.json` and add `'self'` to the end of the CSP value?

**Comment by dibadibadiudiu** [comment]
Great! The problem was successfully solved. thank you very much！🎉

**Comment by dibadibadiudiu** [comment]
@nothingismagick  Hello friend，I encountered the problem of opening the blank after the update.

**Describe the bug**

The app was blank When I updated to v1.0.0-beta.2 and opened app。
`yarn tauri build --debug` show this error

[Error] TypeError: window['e848dfba-4ff6-40ff-b262-6706bda088ce'] is not a function. (In 'window['e848dfba-4ff6-40ff-b262-6706bda088ce']({event: "tauri://resize", payload: {"height":1080,"width":1920}}, 'f5451315-1f7d-4636-ae17-c0bce323145c')', 'window['e848dfba-4ff6-40ff-b262-6706bda088ce']' is undefined)

TypeError: window['e848dfba-4ff6-40ff-b262-6706bda088ce'] is not a function. (In 'window['e848dfba-4ff6-40ff-b262-6706bda088ce']({event: "tauri://focus", payload: null}, '44dadcee-6559-417f-a651-9662a9af433a')', 'window['e848dfba-4ff6-40ff-b262-6706bda088ce']' is undefined)

but run `yarn tauri dev` is ok。

**To Reproduce**
Steps to reproduce the behavior:
1.`yarn tauri build --debug`
2.open app webview console

**Platform and Versions (please complete the following information):**
Operating System - Mac OS, version 11.2.3 X64

Node.js environment
  Node.js - 15.8.0
  @tauri-apps/cli - 1.0.0-beta.1（I've upgraded the latest version 1.0.0-beta.2, but it's still the old version 1.0.0-beta.1）
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 7.5.1
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/dist
/node_modules
/public
/src-tauri
/.git
/src

App
  tauri.rs - 1.0.0-beta.1
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self'
distDir - ../dist
devPath - http://localhost:8080
framework - Vue.js (Vue CLI)
bundler - Webpack

**Comment by nothingismagick** [comment]
can you please edit your package.json, update the @tauri-apps/cli manually, remove your `node_modules` folder and then run `yarn` again?

**Comment by nothingismagick** [comment]
also try this:
```
1. delete file src-tauri/cargo.lock
2. rerun yarn tauri dev
```

**Comment by dibadibadiudiu** [comment]
I've just tried it all, but it still doesn't work.


```
remove node_modules
yarn
delete file src-tauri/cargo.lock
yarn tauri dev
```

**Comment by dibadibadiudiu** [comment]
`yarn tauri dev` 
It works

`yarn tauri build `
 [Error] TypeError: window['e848dfba-4ff6-40ff-b262-6706bda088ce'] is not a function. (In 'window['e848dfba-4ff6-40ff-b262-6706bda088ce']({event: "tauri://resize", payload: {"height":1080,"width":1920}}, 'f5451315-1f7d-4636-ae17-c0bce323145c')', 'window['e848dfba-4ff6-40ff-b262-6706bda088ce']' is undefined)

**Comment by dibadibadiudiu** [comment]
The cause of this problem has been found. The page path caused by the route of Vue is not found.
