### ISSUE TITLE
[bug] tauri not working on the fedora

### ISSUE THREAD

**Issue by sablokrep** [tauri-apps/tauri#13119]
### Describe the bug

i am writing a new application and tauri was working fine previously but now it doesnt seems to be working on the fedora Linux fedora 6.13.8-200.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Mar 23 05:03:09 UTC 2025 x86_64 GNU/Linux. 

I installed all the dependencies, and my rustup is looking like: 
ibch/eVaianalyzerFront » rustup target list --installed
aarch64-apple-ios
wasm32-unknown-unknown
x86_64-apple-ios
x86_64-unknown-linux-gnu

and the package dependencies are looking like
[dependencies]
leptos = { version = "0.7", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
console_error_panic_hook = "0.1.7"
wasm32-unknown-unknown-openbsd-libc = "0.2.0"

However, when i am compiling, it is giving error as 
error[E0463]: can't find crate for `std`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`

and the initial showup page is not coming. I have worked with tauri previously and used the channel routing and dont know why this is happening now?. 

Please kindly help in this regard,
Gaurav 

### Full `tauri info` output

```text
[✔] Environment
    - OS: Fedora 41.0.0 x86_64 (X64) (gnome on wayland)
    ✔ webkit2gtk-4.1: 2.48.0
    ✔ rsvg2: 2.59.2
    ✔ rustc: 1.85.1 (4eb161250 2025-03-15) (Fedora 1.85.1-1.fc41)
    ✔ cargo: 1.85.1 (d73d2caf9 2024-12-31)
    ✔ rustup: 1.28.1 (f9edccde0 2025-03-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 22.14.0
    - npm: 10.9.2

[-] Packages
    - tauri 🦀: 2.4.0
    - tauri-build 🦀: 2.1.0
    - wry 🦀: 0.50.5
    - tao 🦀: 0.32.8
    - tauri-cli 🦀: 2.4.0

[-] Plugins
    - tauri-plugin-opener 🦀: 2.2.6

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
```

### Stack trace

```text

```

**Comment by sablokrep** [comment]
I figured out the problem and the problem is that it is not working with Yew, Leptos and Dioxus and rest it is working with Javascript and Vanilla. Any help that can be shown as how to get it work with Yew, Leptos or Dioxus. Thank you, Gaurav

**Comment by FabianLars** [comment]
Do you maybe have a second rust toolchain installed (for example via dnf or something like homebrew)? I think you can probably check that via `which cargo` or `which rustc`

**Comment by sablokrep** [comment]
I checked and i only have one toolchain installed. See the latest version:
```
 » cargo -V
cargo 1.85.1 (d73d2caf9 2024-12-31)
 » rustc -V
rustc 1.85.1 (4eb161250 2025-03-15) (Fedora 1.85.1-1.fc41)
```
Thank you for the help.

**Comment by FabianLars** [comment]
what about re-installing the wasm target then?
```
rustup target remove wasm32-unknown-unknown
rustup target add wasm32-unknown-unknown
```

i've really only seen this error in those cases:
- target simply not installed
- target broke somehow
- duplicate toolchains with the "wrong" one having the target

If none of those apply here i really don't know what's happening tbh

**Comment by sablokrep** [comment]
I will have that done and will let you know. I also dont know. I previously coded a complete tauri rust application and used dioxus and it was working well. Dont know what happened.
