### ISSUE TITLE
[bug] about this bug  “no field `callback` on type `handle_ipc_message::Message`  ”

### ISSUE THREAD

**Issue by qe-present** [tauri-apps/tauri#13191]
### Describe the bug

When I tried to compile in Tauri2.4.1, this error occurred. but this is easy to solve

### Expected behavior

this is the source code

```Rust
        let request = InvokeRequest {
          cmd: message.cmd,
          callback: message.callback,
          error: message.error,
          url: Url::parse(&request.uri().to_string()).expect("invalid IPC request URL"),
          body: message.payload.into(),
          headers: options.headers.0,
          invoke_key: message.invoke_key,
        };
```
maybe can be solved 

```Rust
        let request = InvokeRequest {
          cmd: message.cmd,
          callback: message.callr,
          error: message.callr,
          url: Url::parse(&request.uri().to_string()).expect("invalid IPC request URL"),
          body: message.payload.into(),
          headers: options.headers.0,
          invoke_key: message.invoke_key,
        };
```
I'm not sure if I can solve it.

### Full `tauri info` output

```text
❯ cargo run
   Compiling tauri v2.4.1
   Compiling tray-icon v0.20.0
   Compiling tauri-plugin-opener v2.2.6                                                                                                                                           
   Compiling start v0.1.0 (D:\start\src-tauri)                                                                                                                                    

**error[E0609]: no field `callback` on type `handle_ipc_message::Message`**                                                                                                           
   --> C:\Users\26644\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-2.4.1\src\ipc\protocol.rs:299:29
    |
299 |           callback: message.callback,
    |                             ^^^^^^^^ unknown field
    |
    = note: available fields are: `cmd`, `callr`, `payload`, `options`, `invoke_key`

**error[E0609]: no field `error` on type `handle_ipc_message::Message`**
   --> C:\Users\26644\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-2.4.1\src\ipc\protocol.rs:300:26
    |
300 |           error: message.error,
    |                          ^^^^^ unknown field
    |
    = note: available fields are: `cmd`, `callr`, `payload`, `options`, `invoke_key`

For more information about this error, try `rustc --explain E0609`.
error: could not compile `tauri` (lib) due to 2 previous errors
```

### Stack trace

```text

```

**Comment by FabianLars** [comment]
can you also share the output of the `tauri info` command as required by the issue template? And if possible, also your Cargo.toml file?

I don't think i've seen this error before tbh 🤔

**Comment by qe-present** [comment]
> can you also share the output of the `tauri info` command as required by the issue template? And if possible, also your Cargo.toml file?
> 
> I don't think i've seen this error before tbh 🤔

yes， but somewhat lengthy


```Rust
        Info Response { status: 302, version: HTTP/1.1, headers: {"content-length": "0", "connection": "keep-alive", "server": "nginx/1.14.0 (Ubuntu)", "date": "Fri, 11 Apr 2025 03:36:29 GMT", "location": "/crate/tauri/latest", "<NOTICE>": "7 HEADERS ARE REDACTED"} }
        Info Redirect (302 Found): GET https://docs.rs/crate/tauri/latest
        Info GET https://docs.rs/crate/tauri/latest
        Info Request { method: GET, uri: https://docs.rs/crate/tauri/latest, version: HTTP/1.1, headers: {"accept-encoding": "gzip", "user-agent": "ureq/3.0.2", "accept": "*/*", "host": "docs.rs"} }
        Info Response { status: 200, version: HTTP/1.1, headers: {"content-type": "text/html; charset=utf-8", "content-length": "107995", "connection": "keep-alive", "server": "nginx/1.14.0 (Ubuntu)", "date": "Fri, 11 Apr 2025 03:36:30 GMT", "<NOTICE>": "8 HEADERS ARE REDACTED"} }
        Info GET https://docs.rs/crate/tauri-build/
        Info Request { method: GET, uri: https://docs.rs/crate/tauri-build/, version: HTTP/1.1, headers: {"accept-encoding": "gzip", "user-agent": "ureq/3.0.2", "accept": "*/*", "host": "docs.rs"} }
        Info Response { status: 308, version: HTTP/1.1, headers: {"content-length": "0", "connection": "keep-alive", "server": "nginx/1.14.0 (Ubuntu)", "date": "Fri, 11 Apr 2025 11:53:24 GMT", "location": "/crate/tauri-build", "<NOTICE>": "7 HEADERS ARE REDACTED"} }
        Info Redirect (308 Permanent Redirect): GET https://docs.rs/crate/tauri-build
        Info GET https://docs.rs/crate/tauri-build
        Info Request { method: GET, uri: https://docs.rs/crate/tauri-build, version: HTTP/1.1, headers: {"accept-encoding": "gzip", "user-agent": "ureq/3.0.2", "accept": "*/*", "host": "docs.rs"} }
        Info Response { status: 302, version: HTTP/1.1, headers: {"content-length": "0", "connection": "keep-alive", "server": "nginx/1.14.0 (Ubuntu)", "date": "Fri, 11 Apr 2025 03:36:30 GMT", "location": "/crate/tauri-build/latest", "<NOTICE>": "7 HEADERS ARE REDACTED"} }
        Info Redirect (302 Found): GET https://docs.rs/crate/tauri-build/latest
        Info GET https://docs.rs/crate/tauri-build/latest
        Info Request { method: GET, uri: https://docs.rs/crate/tauri-build/latest, version: HTTP/1.1, headers: {"accept-encoding": "gzip", "user-agent": "ureq/3.0.2", "accept": "*/*", "host": "docs.rs"} }
        Info Response { status: 200, version: HTTP/1.1, headers: {"content-type": "text/html; charset=utf-8", "content-length": "59244", "connection": "keep-alive", "server": "nginx/1.14.0 (Ubuntu)", "date": "Fri, 11 Apr 2025 03:36:30 GMT", "<NOTICE>": "8 HEADERS ARE REDACTED"} }
        Info GET https://docs.rs/crate/wry/
        Info Request { method: GET, uri: https://docs.rs/crate/wry/, version: HTTP/1.1, headers: {"accept-encoding": "gzip", "user-agent": "ureq/3.0.2", "accept": "*/*", "host": "docs.rs"} }
        Info Response { status: 308, version: HTTP/1.1, headers: {"content-length": "0", "connection": "keep-alive", "server": "nginx/1.14.0 (Ubuntu)", "date": "Fri, 11 Apr 2025 11:53:27 GMT", "location": "/crate/wry", "<NOTICE>": "7 HEADERS ARE REDACTED"} }
        Info Redirect (308 Permanent Redirect): GET https://docs.rs/crate/wry
        Info GET https://docs.rs/crate/wry
        Info Request { method: GET, uri: https://docs.rs/crate/wry, version: HTTP/1.1, headers: {"accept-encoding": "gzip", "user-agent": "ureq/3.0.2", "accept": "*/*", "host": "docs.rs"} }
        Info Response { status: 302, version: HTTP/1.1, headers: {"content-length": "0", "connection": "keep-alive", "server": "nginx/1.14.0 (Ubuntu)", "date": "Fri, 11 Apr 2025 07:35:02 GMT", "location": "/crate/wry/latest", "<NOTICE>": "7 HEADERS ARE REDACTED"} }
        Info Redirect (302 Found): GET https://docs.rs/crate/wry/latest
        Info GET https://docs.rs/crate/wry/latest
        Info Request { method: GET, uri: https://docs.rs/crate/wry/latest, version: HTTP/1.1, headers: {"accept-encoding": "gzip", "user-agent": "ureq/3.0.2", "accept": "*/*", "host": "docs.rs"} }
        Info Response { status: 200, version: HTTP/1.1, headers: {"content-type": "text/html; charset=utf-8", "content-length": "172058", "connection": "keep-alive", "server": "nginx/1.14.0 (Ubuntu)", "date": "Fri, 11 Apr 2025 07:35:02 GMT", "<NOTICE>": "8 HEADERS ARE REDACTED"} }
        Info GET https://docs.rs/crate/tao/
        Info Request { method: GET, uri: https://docs.rs/crate/tao/, version: HTTP/1.1, headers: {"accept-encoding": "gzip", "user-agent": "ureq/3.0.2", "accept": "*/*", "host": "docs.rs"} }
        Info Response { status: 308, version: HTTP/1.1, headers: {"content-length": "0", "connection": "keep-alive", "server": "nginx/1.14.0 (Ubuntu)", "date": "Fri, 11 Apr 2025 11:53:29 GMT", "location": "/crate/tao", "<NOTICE>": "7 HEADERS ARE REDACTED"} }
        Info Redirect (308 Permanent Redirect): GET https://docs.rs/crate/tao
        Info GET https://docs.rs/crate/tao
        Info Request { method: GET, uri: https://docs.rs/crate/tao, version: HTTP/1.1, headers: {"accept-encoding": "gzip", "user-agent": "ureq/3.0.2", "accept": "*/*", "host": "docs.rs"} }
        Info Response { status: 302, version: HTTP/1.1, headers: {"content-length": "0", "connection": "keep-alive", "server": "nginx/1.14.0 (Ubuntu)", "date": "Fri, 11 Apr 2025 03:36:31 GMT", "location": "/crate/tao/latest", "<NOTICE>": "7 HEADERS ARE REDACTED"} }
        Info Redirect (302 Found): GET https://docs.rs/crate/tao/latest
        Info GET https://docs.rs/crate/tao/latest
        Info Request { method: GET, uri: https://docs.rs/crate/tao/latest, version: HTTP/1.1, headers: {"accept-encoding": "gzip", "user-agent": "ureq/3.0.2", "accept": "*/*", "host": "docs.rs"} }
        Info Response { status: 200, version: HTTP/1.1, headers: {"content-type": "text/html; charset=utf-8", "content-length": "73157", "connection": "keep-alive", "server": "nginx/1.14.0 (Ubuntu)", "date": "Fri, 11 Apr 2025 03:36:31 GMT", "<NOTICE>": "8 HEADERS ARE REDACTED"} }
        Info GET https://docs.rs/crate/tauri-plugin-opener/
        Info Request { method: GET, uri: https://docs.rs/crate/tauri-plugin-opener/, version: HTTP/1.1, headers: {"accept-encoding": "gzip", "user-agent": "ureq/3.0.2", "accept": "*/*", "host": "docs.rs"} }
        Info Response { status: 308, version: HTTP/1.1, headers: {"content-length": "0", "connection": "keep-alive", "server": "nginx/1.14.0 (Ubuntu)", "date": "Fri, 11 Apr 2025 11:53:34 GMT", "location": "/crate/tauri-plugin-opener", "<NOTICE>": "7 HEADERS ARE REDACTED"} }
        Info Redirect (308 Permanent Redirect): GET https://docs.rs/crate/tauri-plugin-opener
        Info GET https://docs.rs/crate/tauri-plugin-opener
        Info Request { method: GET, uri: https://docs.rs/crate/tauri-plugin-opener, version: HTTP/1.1, headers: {"accept-encoding": "gzip", "user-agent": "ureq/3.0.2", "accept": "*/*", "host": "docs.rs"} }
        Info Response { status: 302, version: HTTP/1.1, headers: {"content-length": "0", "connection": "keep-alive", "server": "nginx/1.14.0 (Ubuntu)", "date": "Fri, 11 Apr 2025 09:33:01 GMT", "location": "/crate/tauri-plugin-opener/latest", "<NOTICE>": "7 HEADERS ARE REDACTED"} }
        Info Redirect (302 Found): GET https://docs.rs/crate/tauri-plugin-opener/latest
        Info GET https://docs.rs/crate/tauri-plugin-opener/latest
        Info Request { method: GET, uri: https://docs.rs/crate/tauri-plugin-opener/latest, version: HTTP/1.1, headers: {"accept-encoding": "gzip", "user-agent": "ureq/3.0.2", "accept": "*/*", "host": "docs.rs"} }
        Info Response { status: 200, version: HTTP/1.1, headers: {"content-type": "text/html; charset=utf-8", "content-length": "58389", "connection": "keep-alive", "server": "nginx/1.14.0 (Ubuntu)", "date": "Fri, 11 Apr 2025 09:33:02 GMT", "<NOTICE>": "8 HEADERS ARE REDACTED"} }

[✔] Environment
    - OS: Windows 10.0.26200 x86_64 (X64)
    ✔ WebView2: 135.0.3179.54
    ✔ MSVC: Visual Studio Enterprise 2022
    ✔ rustc: 1.85.0 (4d91de4e4 2025-02-17)
    ✔ cargo: 1.85.0 (d73d2caf9 2024-12-31)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 23.7.0
    - pnpm: 10.7.0
    - yarn: 1.22.21
    - npm: 10.9.2

[-] Packages
    - tauri 🦀: 2.4.1
    - tauri-build 🦀: 2.1.1
    - wry 🦀: 0.50.5
    - tao 🦀: 0.32.8
    - @tauri-apps/api : 2.4.0 (outdated, latest: 2.4.1)
    - @tauri-apps/cli : 2.4.0 (outdated, latest: 2.4.1)

[-] Plugins
    - tauri-plugin-opener 🦀: 2.2.6
    - @tauri-apps/plugin-opener : 2.2.6

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
                     
```

the Cargo.toml

```Rust
[package]
name = "start"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2024"


[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["image-png", "devtools", "tray-icon", "unstable", "tracing"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

```

**Comment by qe-present** [comment]
meybe I understand it
in source code,the  struct `Message`  
```Rust
    #[derive(Deserialize)]
    struct Message {
      cmd: String,
      callback: CallbackFn,
      error:CallbackFn,
      payload: serde_json::Value,
      options: Option<RequestOptions>,
      #[serde(rename = "__TAURI_INVOKE_KEY__")]
      invoke_key: String,
    }
```
but in  my source code
```Rust
    #[derive(Deserialize)]
    struct Message {
      cmd: String,
      callr:CallbackFn
      payload: serde_json::Value,
      options: Option<RequestOptions>,
      #[serde(rename = "__TAURI_INVOKE_KEY__")]
      invoke_key: String,
    }
```
maybe is my question ,because I could alter the source code and forget to back.
so I delete the tauri2.4.1 and Re-download 
complie success！！！
😜😜😜😜😜😜😜😜😜
