### ISSUE TITLE
[bug] Error in web console - window.__TAURI_IPC__ is not a function

### ISSUE THREAD

**Issue by MstrVLT** [tauri-apps/tauri#8214]
### Describe the bug

Fresh install MacOS 10.14 and rust and tauri. Calling command from the frontend not working and console say - window.__TAURI_IPC__ is not a function. Safari update to 14.1.2

![Screenshot 2023-11-12 at 14 43 32](https://github.com/tauri-apps/tauri/assets/10544388/eb9851aa-5a0f-40c7-ada2-c71c58c8218e)

### Reproduction

Well I followed the guide, step by step and I chose vue + javascript

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 10.14.6 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 20.9.0
    - yarn: 1.22.19
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.6

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Since you mentioned Safari, you did not try to open your frontend in your browser right? Tauri's apis only work in actual Tauri windows.

**Comment by MstrVLT** [comment]
> Since you mentioned Safari, you did not try to open your frontend in your browser right? Tauri's apis only work in actual Tauri windows.

I debug and this screenshot inside app and i see window.__TAURI_IPC__ is undefinded 
if you need proof of my words I can record a video for you.

I also tried project using wry (https://github.com/tauri-apps/wry/blob/wry-v0.24.4/examples/custom_titlebar.rs) and ipc_handler work well

I also tried set "withGlobalTauri": true - but nothing has changed.

It's all very sad tauriapp is a good and it works great on linux and windows

**Comment by FabianLars** [comment]
Would it be possible to upload the project to github so we can take a look? Even if it's a fresh create-tauri-project.

Alternatively some more exact reproduction steps? This is _not_ normal behavior so something went wrong somewhere but i can't seem to reproduce it.

**Comment by MstrVLT** [comment]
@FabianLars I understand that macos10.14 is pretty outdated and it's hard to find a computer with it I can give remote access for you to my computer if its needed

**Comment by MstrVLT** [comment]
> Would it be possible to upload the project to github so we can take a look? Even if it's a fresh create-tauri-project.
> 
> Alternatively some more exact reproduction steps? This is _not_ normal behavior so something went wrong somewhere but i can't seem to reproduce it.



[this](https://github.com/MstrVLT/test_app_macos_)

**Comment by MstrVLT** [comment]
https://github.com/tauri-apps/tauri/assets/10544388/236cf4d9-d94c-4460-88e3-2d18f3946834

![img](https://github.com/tauri-apps/tauri/assets/10544388/d2d41bc1-5b01-49a8-8d9f-f3de5c8ff363)

**Comment by FabianLars** [comment]
Your api package seems to be outdated: https://github.com/MstrVLT/test_app_macos_/blob/master/yarn.lock#L125
Can you make sure it's on 1.5 too like all your other tauri dependencies?

**Comment by MstrVLT** [comment]
> Your api package seems to be outdated: https://github.com/MstrVLT/test_app_macos_/blob/master/yarn.lock#L125 Can you make sure it's on 1.5 too like all your other tauri dependencies?

I deleted the node_modules and target folders. changed in package.json and cargo.toml to 1.5  
And nothing changed 
`[Error] SyntaxError: Unexpected token '.'
	(anonymous function)
[Error] Unhandled Promise Rejection: TypeError: window.__TAURI_IPC__ is not a function. (In 'window.__TAURI_IPC__({ cmd: e2, callback: o, error: c, ...r })', 'window.__TAURI_IPC__' is undefined)
	logError (vue.js:1615)
	handleError (vue.js:1602)
	(anonymous function) (vue.js:1563)
	promiseReactionJob`

**Comment by MstrVLT** [comment]
@FabianLars I tried opening the @tauri-apps_api_tauri.js folder on mac10.14 and there is nothing inside, on a linux system there are two more js files inside that were not there on mac

mac10.14 
![2023-11-13 13 45 28](https://github.com/tauri-apps/tauri/assets/10544388/a1ccdab3-029f-4813-9165-8680063ac58a)

Linux
![2023-11-13 13 45 33](https://github.com/tauri-apps/tauri/assets/10544388/7bbd87b5-4c42-4a9d-84e9-8d2fb6424549)

**Comment by yuanhaotian** [comment]
所以windows 上跑就没这问题吗？

**Comment by yuanhaotian** [comment]
Have you solved it? I have this problem too.
解决了吗，我也出这问题

**Comment by MstrVLT** [comment]
> Have you solved it? I have this problem too.
> 解决了吗，我也出这问题

Problem still exists ((

**Comment by gentean** [comment]
me too

**Comment by sttk3** [comment]
I was also troubled by this phenomenon, but it worked on macOS 10.14 by restricting Tauri version within the 1.4 series in Cargo.toml.

```
[dependencies]
tauri = { version = "~1.4", features = ["shell-open"] }
```
